/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_laz_binguslite_BingusLite */

#ifndef _Included_com_laz_binguslite_BingusLite
#define _Included_com_laz_binguslite_BingusLite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_laz_binguslite_BingusLite
 * Method:    initialize
 * Signature: (Ljava/lang/ClassLoader;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_laz_binguslite_BingusLite_initialize
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
